kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  namespace: planespotter
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
